version: '3.6'
services:
  website:
    container_name: website
    build: ./website
    restart: unless-stopped
    volumes:
      - ./website:/usr/src/app
    expose:
      - '3000'
    env_file: .env
    command: bash -c "yarn build && yarn start"
    networks:
      - 3ab3

  member:
    container_name: member
    build: ./member
    restart: unless-stopped
    volumes: 
      - ./member/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - '3001'
    env_file: .env
    networks:
      - 3ab3

  api:
    container_name: api
    restart: unless-stopped
    build: ./server/api/
    expose:
      - '4000'
    volumes:
      - ./server/prisma/generated:/usr/src/app/src/generated
      - /var/local/3ab3/storage/:/usr/src/app/storage
      - ./server/api/src:/usr/src/app/src
    networks:
      - 3ab3
    command: yarn start
    environment:
      - PRISMA_HOST=http://prisma
    env_file: .env

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    restart: unless-stopped
    ports:
      - '$PRISMA_PORT:$PRISMA_PORT'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: $PRISMA_PORT
        databases:
          default:
            connector: postgres
            host: postgres
            port: $POSTGRES_PORT
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true
            rawAccess: false

    networks:
      - 3ab3

  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/local/3ab3/postgres/:/var/lib/postgresql/data
    networks:
      - 3ab3

  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '4000:4000'
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./server/proxy/nginx.prod.conf:/etc/nginx/nginx.conf
      - /var/local/3ab3/storage/:/usr/src/app/storage
    networks:
      - 3ab3

volumes:
  postgres:
  storage:

networks:
  3ab3:
    driver: bridge
    name: 3ab3-network
