version: '3.6'
services:
  api:
    container_name: api
    build: ./server/api/
    ports:
      - "4000:4000"
    volumes:
      - ./server/prisma/generated:/usr/src/app/src/generated
    networks:
      - 3ab3
    command: yarn start

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.26
    restart: unless-stopped
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    networks:
      - 3ab3

  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - 3ab3


volumes:
  postgres:

networks:
  3ab3:
    driver: bridge
    name: 3ab3-network
