version: '3.6'
services:
  api:
    container_name: api
    build: ./server/api/
    expose:
      - "4000"
    volumes:
      - ./server/prisma/generated:/usr/src/app/src/generated
      - /var/local/3ab3/storage/:/usr/src/app/storage
      - ./server/api/src:/usr/src/app/src
    networks:
      - 3ab3
    command: yarn start
    environment:
      - ACCESS_TOKEN_SECRET
      - ACCESS_TOKEN_EXPIRATION
      - LOGIN_TOKEN_SECRET
      - LOGIN_TOKEN_EXPIRATION
      - STORAGE_ROOT
      - MAILGUN_DOMAIN
      - MAILGUN_API_SECRET
      - PRISMA_SERVICE_SECRET
      - MEMBER_CLIENT_URL

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    restart: unless-stopped
    ports:
    - "$PRISMA_PORT:$PRISMA_PORT"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: $PRISMA_PORT
        databases:
          default:
            connector: postgres
            host: postgres
            port: $POSTGRES_PORT
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true
            rawAccess: false

    networks:
      - 3ab3

  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - /var/local/3ab3/postgres/:/var/lib/postgresql/data
    networks:
      - 3ab3

volumes:
  postgres:
  storage:

networks:
  3ab3:
    driver: bridge
    name: 3ab3-network
