version: '3.6'
services:
  api:
    container_name: api
    build: ./server/api/
    expose:
      - "4000"
    volumes:
      - ./server/prisma/generated:/usr/src/app/src/generated
    networks:
      - 3ab3
    command: yarn start
    environment:
      - ACCESS_TOKEN_SECRET
      - ACCESS_TOKEN_EXPIRATION

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.26
    restart: unless-stopped
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: $POSTGRES_PORT
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true
    networks:
      - 3ab3

  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - /var/local/3ab3/postgres/:/var/lib/postgresql/data
    networks:
      - 3ab3

  proxy:
    container_name: proxy
    build: ./server/proxy
    ports:
     - "4000:4000"
    volumes:
      - /var/local/3ab3/storage/:/usr/src/app/storage
    networks:
     - 3ab3


volumes:
  postgres:
  storage:

networks:
  3ab3:
    driver: bridge
    name: 3ab3-network
